spring.application.name=recall
recall.gcp-project-id=recall-25902
spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.name=recall-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=ASYNC
spring.ai.mcp.server.instruction="This is the recall MCP server"
spring.ai.mcp.server.streamable-http.mcp-endpoint=/api/mcp